# action.yml
name: 'AWS ECR Create'
description: 'Create an ECR repo in AWS'
inputs:
  allowed_accounts:
    description: List of AWS account id's that have read access to this repo

outputs:
  arn:
    description: AWS ARN of the ECR repository

  uri:
    description: Docker URI of the ECR repository

runs:
  using: 'docker'
  image: 'Dockerfile'
